<div class="span4">
    <div class="well" style="padding: 8px 0;">
        <?php if (C_Security_Authenticate::loginControl()):
        $user = C_Session::getUser();?>
        <h3><? C_Session::getUser()->getName(); ?></h3>
            <? if ($user->isApproved() == 1): ?>
        
        <? elseif ($user->isApproved() == 0): ?>
        <div class="alert alert-block">
            <h4 class="alert-heading">Dikkat!</h4>
            Bu karakter henüz onaylanmamıştır.
        </div>
        <? else: ?>
        <div class="alert alert-error">
            <h4 class="alert-heading">Dikkat!</h4>
            Bu karakter reddedilmiştir.
        </div>
        <? endif; ?>
    <? else: ?>

    <? endif; ?>
    </div>
</div>