<div class="span4">
    <div class="well">
        <?php if (C_Security_Authenticate::loginControl()):
        $user = C_Session::getUser();?>
        <h4><?= $user->getName(); ?>
            <? if ($user->isApproved() == 1): ?>
            <span class="label label-success">Onaylandı</span>
        <? elseif ($user->isApproved() == 0): ?>
            <span class="label label-warning">Beklemede</span>
        <? else: ?>
            <span class="label label-important">Reddedildi</span>
        <? endif; ?>
        </h4>
        <ul class="thumbnails">
            <li class="span1 centered">
                <div class="thumbnail">
                    <? $user->printSkin(55, 100); ?>
                </div>
                <p>Yaş:<?= $user->getAge(); ?></p>
            </li>
        </ul>
    <? else: ?>

    <? endif; ?>
    </div>
</div>