<?php
$userID = C_Security_Filter::queryFilter(C_Security_Filter::numericFilter($_GET['userid']));
$user = new M_User_Regular();
if (!$user->initWithID($userID) || !$user->isApproved()) {
    header("location: ".C_Link::create("management", "index", array("result"=>"-5")));
    exit();
}
$user->initPlayer();
$player = $user->getPlayer();
$playerFieldsArray = $player->getFieldsArray();
$newFieldValues = array();
foreach($playerFieldsArray as $fieldKey => $fieldValue) {
    if (is_numeric($fieldKey)) continue;
    print("KEY: ".$fieldKey. "<br>");
    print("POST: ".$_POST['edit_'.$fieldKey]. "<br>");
    $newFieldValues[$fieldKey] = $_POST['edit_'.$fieldKey];
}
$user->editPlayer($newFieldValues);
//header("location: ".C_Link::create("management", "index", array("result"=>"5")));