<?php
$userID = C_Security_Filter::queryFilter(C_Security_Filter::numericFilter($_GET['userid']));
$user = new M_User_Regular();
if (!$user->initWithID($userID) || !$user->isApproved()) {
    header("location: ".C_Link::create("management", "index", array("result"=>"-5")));
    exit();
}
$user->initPlayer();
$player = $user->getPlayer();
$playerFieldsArray = $player->getFieldsArray();
$newFieldValues = array();
foreach($playerFieldsArray as $fieldKey => $fieldValue) {
    $newFieldValues[$fieldKey] = $_POST[$fieldKey];
}
$user->editPlayer($newFieldValues);
header("location: ".C_Link::create("management", "index", array("result"=>"5")));