<?php

$userID = C_Security_Filter::queryFilter(C_Security_Filter::numericFilter($_GET['userid']));
$user = new M_User_Regular();
if ($user->initWithID($userID)) {
    if ($user->createPlayerFromAndApproveSelf()) {
        header("location: ".C_Link::create("management", "index", array("result"=>"1")));
        exit();
    }
}
header("location: ".C_Link::create("management", "index", array("result"=>"-1")));