<?php
$userID = C_Security_Filter::queryFilter(C_Security_Filter::numericFilter($_GET['userid']));
$user = new M_User_Regular();
if (!$user->initWithID($userID) || !$user->isApproved()) {
    header("location: ".C_Link::create("management", "index", array("result"=>"-5")));
    exit();
}
$user->initPlayer();
$user->initTEST("19");
$player = $user->getPlayer();
$playerFieldsArray = $player->getFieldsArray();
?>
<form class="form-horizontal" name="form_playeredit" id="form_playeredit" action="<?=C_Link::create("management", "applyedit");?>" method="POST">
    <fieldset>
        <legend><?=C_T::_("Oyuncu Düzenleme Formu");?></legend>
        <? foreach($playerFieldsArray as $fieldKey => $fieldValue): ?>
        <div class="control-group">
            <label class="control-label" for="edit_<?=$fieldKey;?>"><?=$fieldKey;?></label>
            <div class="controls">
                <input type="text" class="input-xlarge" id="edit_<?=$fieldKey;?>" name="edit_<?=$fieldKey;?>" value="<?=$fieldValue;?>"/>
            </div>
        </div>
        <? endforeach; ?>
        <div class="form-actions">
            <button type="submit" class="btn btn-primary" id="submit_edit">Düzenle!</button>
        </div>
    </fieldset>
</form>