<?php

$userID = C_Security_Filter::queryFilter(C_Security_Filter::numericFilter($_GET['userid']));
$user = new M_User_Regular();
if ($user->initWithID($userID)) {
    if ($user->getRole()->canAccessManagementPanel())
        if ($user->fireAdmin()) {
            header("location: ".C_Link::create("management", "index", array("result"=>"4")));
            exit();
        }
    else
        if ($user->hireAdmin()) { print "zwww";
            header("location: ".C_Link::create("management", "index", array("result"=>"3")));
            exit();
        }
}
//header("location: ".C_Link::create("management", "index", array("result"=>"-3")));