<div class="span12">
    <div class="hero-unit">
        <h1>Sroleplay</h1>
        <p>Server'ımıza nazar değmesin!</p>
    </div>
</div>
<div class="span8">
<?php
    if (C_Security_Filter::stringFilter(C_Security_Filter::queryFilter($_GET['logout']))=="successful"):
?>
    <div class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?=C_T::_("Çıkış başarılı!")?></div>
        <?php
    elseif (C_Security_Filter::stringFilter(C_Security_Filter::queryFilter($_GET['register']))=="successful"):
    ?>
    <div class="alert alert-success"><button class="close" data-dismiss="alert">×</button><?=C_T::_("Başarıyla üye oldunuz!")?></div>
        <?
        endif;
        ?>
<h2>
    Sroleplay'e hoş geldiniz!
</h2>
    <p>
        Bu bir San Andreas server'ıdır. Hemen üye olun.
    </p>
</div>